### PR TITLE
Added 'tibble' handling

### LINKED ISSUE #67: error with tbl_df
hi there,

it seems the functions lmBF, ttestBF, etc. do not working with an object of class "tbl_df" from the dplyr package.

``` r
library('dplyr')
library('BayesFactor')

dat = data.frame(y = rnorm(100), x = rnorm(100))
lmBF(y ~ x, data = tbl_df(dat)) # errors
```

The error is "Dependent variable must be numeric", which is especially confusing. On another occasion, I got 

> Error in (function (classes, fdef, mtable)  : unable to find an inherited method for function ‘compare’ for signature ‘"BFlinearModel", "missing", "tbl_df"’

which is when I realized the issue. I think it should work for tbl_df's too, since that is what many people's new data.frame is.

kind regards,
Fabian

ps.: I was wondering how far you guys are with implementing generalized linear models. Any updates? :)

### LINKED ISSUE #80: Incompatibility with tibbles
I ran into an error whereby if you pass `lmBF` a [tibble](https://cran.r-project.org/web/packages/tibble/index.html) (e.g. as output by `dplyr`), one receives an error like:

``` r
result <- lmBF(y~x1*x2, dat)

Error in checkFormula(formula, data, analysis = "lm") : 
  Dependent variable must be numeric.
```

The dependent variable is numeric, and shows as such in any way you care to view the data.

The error can be fixed by explicitly changing the tibble to a dataframe:

``` r
result <- lmBF(y~x1*x2, as.data.frame(dat))
```

It would be good if the BayesFactor package could handle this internally, because the error message is rather cryptic and if one inspects the object, the dependent variable is indeed numeric. I don't know however, if this is a problem on your side or with tibble.

### PR DESCRIPTION
**Pull request by jonathon-love**
fixes #67
fixes #80

### CODE REVIEW

**Comment by richarddmorey** [comment]
This is obviously the easiest way to do this, but because I don't use tbl_df I'm not sure whether this will yield unexpected behaviour in the conversion to a data.frame. I think we should at least note that something was done, in case there is a loss if information somewhere.

**Comment by jonathon-love** [comment]
yeah, makes sense. i was thinking "but tibbles are compatible with data frames in every way", but that's clearly not the case, otherwise we wouldn't be in this situation. what if i add a:

    warning('data coerced from tibble to data frame')

**Comment by richarddmorey** [comment]
That would be ok I think.

**Comment by jonathon-love** [comment]
you hate tibbles?

**Pull request merged**
