### PR TITLE
Added support for special chars (spaces, etc.) in column names

### PR DESCRIPTION
**Pull request by jonathon-love**
hi rich,

this commit adds support for special chars, spaces, etc. in formulas and column names. the meat and potatoes of this is the `composeTerm()` and `composeTerms()` functions, which appropriately escape names for use in formulas.

i've also had to add some base64 code, because the `model.Matrix()` function does not support special chars either (and i haven't had good success with getting in touch with the authors of that package).

you'll see in `test-specialchars.R` all the cases i test. i think that's all of the relevant code paths, but it's possible you might know of a couple that i've missed (either way, there's little chance of a regression, so it's not critical that everything is spot-on in this commit ... although that's always nice)

### CODE REVIEW

**Comment by richarddmorey** [comment]
I noted that you rewrote `centerContinuousColumns` with a `for` loop instead of an `lapply`, so I tested it. My old code appears to be substantially faster for larger data frames.

    N = 1000 
    M = 10000
    
    x <- rnorm(N*M)
    dim(x) = c(N,M)
    X1 = X2 = data.frame(x)

Test the `for` loop:

    system.time({
    for (colName in colnames(X1)) {
            column <- X1[[colName]]
          if ( ! is.factor(column))
              X1[[colName]] = column - mean(column)
          }
    })
        user  system elapsed 
     10.641   0.719  11.701 

Test the `lapply`:

    system.time({
    X3 = lapply(X2,function(colmn){		 
          if(is.factor(colmn)){		 
            return(colmn)		 
            }else{		 
              return(colmn - mean(colmn))		 
          }		 
        })		
    X3 = data.frame(X3)
    })
    
       user  system elapsed 
      0.781   0.016   0.831 

...and the results are identical:

    identical(X1,X3)
    [1] TRUE

Is there a reason other than clarity that you changed it?

**Comment by jonathon-love** [comment]
ah, good catch!

yeah, the call to `data.frame()` is a problem.

```
return(data.frame(mycols))
```

it mangles names. some R data frame operations mangle names, and others don't.

so i just rewrote it, neively not realising it was performance critical.

i'll commit a fix tomorrow.

cheers

**Comment by jonathon-love** [comment]
for future reference, this PR was a good candidate for a 'squash-merge' (you can choose 'squash-merge' [you can choose Squash merge in GH with the drop down menu to the right of the merge button])

my second commit was just a fix to the previous commit, and so that doesn't need to go into BF commit history, squashing them combines them into a single clean commit.

alternatively, i could have squashed them together when i was making the second commit, but then you would have had to evaluate the *whole* PR again.

so a squash-merge is the best of both worlds; you get to see separate commits as i fix things, and the history for your repo only contains clean meaningful commits.

**Comment by richarddmorey** [comment]
mmmmmm, was not familiar with that, thanks

**Pull request merged**
